#!/bin/bash -eu

# stop existing waydroid session
waydroid session stop

# Cleanup waydroid shortcuts
sudo rm -f ~/.local/share/applications/*.desktop
sudo rm -f /usr/share/applications/python*.desktop
sudo rm -f /usr/share/applications/vim*.desktop
sudo rm -f /usr/share/applications/waydroid*.desktop